### ISSUE TITLE
Support installation using pip

### ISSUE THREAD

**Issue by jonasoh** [jonasoh/spiro#11]
Preferably, installing spiro can be done using a one-liner.

**Comment by AlyonaMinina** [comment]
Mark suggested to make an image of the SD card with all components included. What do you think?

It would be cool to also add three prompts for the user after the SD flashing is complete:
-sudo apt-get update 
-set the correct time zone (critical for the experiments)
-pull updates from the spiro repository

**Comment by jonasoh** [comment]
I was originally considering that we'd distribute the complete system as a filesystem image. However, I no longer think this is a good idea due to the fact that maintaining such an image is a lot of work and most likely we will end up with an outdated operating system image within a very short while. 

I think that the Raspbian people do an excellent job in making the OS continually easier to install and maintain. The raspi-config utility is all that would be required in terms of setting things up (network, time zone, SSH, password, etc). Then spiro is installed using a one-line command and automatically fetches its own dependencies. At least this is how I imagine it right now.

**Comment by jonasoh** [comment]
This was implemented in commits https://github.com/jonasoh/spiro/commit/c0fedee3780b894c8425c080baa4cfc79d8de156 and https://github.com/jonasoh/spiro/commit/bc22a80de40a9509584e7014fd2dc744366f95c7. Installing spiro on a new system is now as easy as `pip3 install git+https://github.com/jonasoh/spiro`.
