### ISSUE TITLE
Suggestion for an automated alignment script

### ISSUE THREAD

**Issue by AlyonaMinina** [jonasoh/spiro#19]
**Suggestion for an automated alignment script**

- find the tiny dick (it is bolted to the cube now, so we can estimate approx. how many steps it is away from the initial position)

- make estimated number of steps

- Match reference points or text on the cube (scale bar should be always in the pic?) to the existing reference grid

- If doesn't match make more steps or step back (is it possible to estimate what direction and is preferential?)

- Re-match, if ok-> write the total n of steps made from tiny dick to the initial position into spiro.py

**Comment by jonasoh** [comment]
Do we still want this? I think it is probably not necessary with the new more precise motor code and the crude start position calibration view. Admittedly it is a more manual process, but I imagine that one very rarely, if ever, would actually need to do it.

**Comment by jonasoh** [comment]
I hereby decide that the current UI is enough. If, after building a number of system, it appears that we need an automated calibration thingy we may reopen this issue.
