### ISSUE TITLE
Message about disk space available for the experiment

### ISSUE THREAD

**Issue by AlyonaMinina** [jonasoh/spiro#21]
This has to be done when spiro.py  is just started, before taking any images

-  calculate total space needed for the experiment:
     number of images calculated from the current flags: (-l *24*60)/-d
     a single jpeg is just below 4 Mb

- pull info about available space on SD. Mark suggests using [shutil.disk_usage](https://docs.python.org/3/library/shutil.html)

- print a message to user " total disk space required: xx, total disk space available: yy. Proceed y/n"

**Comment by jonasoh** [comment]
Good idea although we will not issue a prompt for the user upon start of the program as this whould interefere with nohup.
