### ISSUE TITLE
Internal server error while initiating experiment control

### ISSUE THREAD

**Issue by AlyonaMinina** [jonasoh/spiro#23]
![image](https://user-images.githubusercontent.com/47862925/61788782-45319600-ae13-11e9-8428-fa2ff49b875c.png)

**Comment by jonasoh** [comment]
Need more info on this one. Steps to reproduce?

**Comment by jonasoh** [comment]
Realized the error. This was fixed in 92f19cffd75c3fd11179652e905400bdd9464bb3.
