### ISSUE TITLE
Write failed when starting experiment

### ISSUE THREAD

**Issue by mmjulkowska** [jonasoh/spiro#34]
Hi guys - thanks a lot for sharing the resources. I am able to connect to SPIRO through WiFi network, but when I try to run the experiment I get the "Error: Write failed", and no images are being saved on my Raspberry Pi computer. I checked i2cdetect -y 1 and none of the ports are engaged. Any advice on how to proceed would be highly appreciated!

**Comment by jonasoh** [comment]
Hi,
could you provide me with some more information to help me figure out what is going on? Usually, the "Error: Write failed" message is nothing to worry about. I think it comes from the way we're sending focusing commands to the camera, and as long as focusing is working in the web UI, it should be safe to ignore it.

Anyway, to collect some data. First, run
`spiro --toggle-debug`
to enable debug logging. It should tell you debug mode is on. 

After that, please restart the web UI from System settings. Try again to start an experiment. After it fails (e.g., let it run through one cycle of image collection), run the following command to get the log output:
`journalctl --user-unit=spiro -n 100`

The proper way to run i2cdetect will depend on the exact type of camera you have. You should be able to see active ports using `i2cdetect -y 0` if nothing shows up with `-y 1`.

Get back to me with the output and we can work from there.

**Comment by mmjulkowska** [comment]
Thanks for the info - I ran the SPIRO in the debug mode, and here is the output when I run `journalctl --user-unit=spiro -n 100`.

```
-- Logs begin at Fri 2022-01-14 09:11:32 EST, end at Fri 2022-01-14 09:14:06 EST
Jan 14 09:11:43 raspberrypi systemd[517]: Started SPIRO control software.
Jan 14 09:12:06 raspberrypi spiro[584]: Error: Write failed
Jan 14 09:12:06 raspberrypi spiro[584]: Starting web UI.
Jan 14 09:13:54 raspberrypi spiro[584]: Starting new experiment.
Jan 14 09:13:54 raspberrypi spiro[584]: Starting experiment.
Jan 14 09:13:54 raspberrypi spiro[584]: Finding initial position.
Jan 14 09:14:00 raspberrypi spiro[584]: Found initial position.
Jan 14 09:14:03 raspberrypi spiro[584]: Daytime estimation mean value: 24.677504
Jan 14 09:14:03 raspberrypi spiro[584]: Determining white balance.
Jan 14 09:14:05 raspberrypi spiro[584]: Capturing /home/pi/2022.01.14 spiro/plat
Jan 14 09:14:06 raspberrypi spiro[584]: /usr/lib/python3/dist-packages/picamera/
Jan 14 09:14:06 raspberrypi spiro[584]:   width, height, fwidth, fheight)))
Jan 14 09:14:06 raspberrypi spiro[584]: Experiment stopped.
```

Currently, I don't have the automatic focus camera on (it didn't engage - I think I accidentally ordered the wrong model), and decided to continue with the manual/forced focus RaspiCamera. I can see the preview now from the camera no problem - and every time I try to run an experiment, it does generate a folder on my pi with plate1/plate2/plate3/plate4 sub-folders, but no images.  

Thanks for your kind help!

**Comment by jonasoh** [comment]
Are you using the V1 or V2 Raspberry Pi camera? SPIRO is not designed to work with the V1, but it should be easy to accommodate that. 

I think I have an idea where the crash occurs, but unfortunately the lines in your log file output are truncated. Could you please rerun the command as `journalctl --user-unit=spiro -n 100 --no-pager`?

**Comment by mmjulkowska** [comment]
Thanks again - we are using the [Arducam 5MP Camera for Raspberry Pi, 1080P HD OV5647 Camera Module V1 for Pi 4, Raspberry Pi 3, 3B+, and Other A/B Series, Pi Zero & W](https://www.amazon.com/Arducam-Megapixels-Sensor-OV5647-Raspberry/dp/B012V1HEP4/ref=sxin_7?ascsubtag=amzn1.osa.6841ead2-0efd-412b-bdc9-34a212bd9543.ATVPDKIKX0DER.en_US&creativeASIN=B012V1HEP4&cv_ct_cx=Raspberry+pi+camera&cv_ct_id=amzn1.osa.6841ead2-0efd-412b-bdc9-34a212bd9543.ATVPDKIKX0DER.en_US&cv_ct_pg=search&cv_ct_wn=osp-single-source-gl-ranking&dchild=1&keywords=Raspberry+pi+camera&linkCode=oas&pd_rd_i=B012V1HEP4&pd_rd_r=faedd1d2-daae-4af4-9e83-3094d2c2db93&pd_rd_w=0vhEY&pd_rd_wg=r7tnW&pf_rd_p=215d02cd-1dfa-4f52-adfa-365154472adf&pf_rd_r=K62BSC2B912RB7J3HAA1&qid=1597942360&s=electronics&sr=1-3-d9dc7690-f7e1-44eb-ad06-aebbef559a37&tag=androidcentralosp-20)

Also - please see below the new log file lines:

```
-- Logs begin at Fri 2022-01-14 09:11:32 EST, end at Sat 2022-01-15 09:53:05 EST. --
Jan 14 09:16:10 raspberrypi systemd[512]: Started SPIRO control software.
Jan 14 09:16:29 raspberrypi spiro[573]: Error: Write failed
Jan 14 09:16:29 raspberrypi spiro[573]: Starting web UI.
Jan 15 09:52:45 raspberrypi spiro[573]: Starting new experiment.
Jan 15 09:52:45 raspberrypi spiro[573]: Starting experiment.
Jan 15 09:52:45 raspberrypi spiro[573]: Finding initial position.
Jan 15 09:52:59 raspberrypi spiro[573]: Found initial position.
Jan 15 09:53:01 raspberrypi spiro[573]: Daytime estimation mean value: 17.7073828125
Jan 15 09:53:02 raspberrypi spiro[573]: Determining white balance.
Jan 15 09:53:04 raspberrypi spiro[573]: Capturing /home/pi/2022.01.15 spiro/plate1/plate1-20220115-095300-day.png.
Jan 15 09:53:05 raspberrypi spiro[573]: /usr/lib/python3/dist-packages/picamera/encoders.py:544: PiCameraResolutionRounded: frame size rounded up from 2592x1944 to 2592x1952
Jan 15 09:53:05 raspberrypi spiro[573]:   width, height, fwidth, fheight)))
Jan 15 09:53:05 raspberrypi spiro[573]: Experiment stopped.
```

Thanks again for your kind help!

**Comment by jonasoh** [comment]
I see. We do not officially support that model, but we have used a similar one previously. I've added some code that should enable you to use that camera. Could you please try to update the control software to this fixed version by issuing the commands:
```
systemctl --user stop spiro
sudo pip3 install -U git+https://github.com/jonasoh/spiro@issue34#egg=spiro
systemctl --user start spiro
```

Hopefully it will solve your problem. Get back to me with the log output if you're still not getting any images.

**Comment by mmjulkowska** [comment]
Thanks so, so much for this! Yes - it is working well right now! 

One more question - how do I set time for LED screen to be on/off? I missed this in the instructions.

**Comment by jonasoh** [comment]
Great to hear that it is working! Hope you will find good uses for your SPIRO :) I would consider upgrading the camera at some point to the [8 MP Arducam module](https://www.arducam.com/product/arducam-imx219-auto-focus-camera-module-drop-in-replacement-for-raspberry-pi-v2-and-nvidia-jetson-nano-camera/), it provides a much nicer user experience. With differences in agar thickness, adjustment of imaging distance, etc, it quickly becomes cumbersome to manually adjust the focus. You'll need a standard Raspberry pi V2 camera as the carrier board for the Arducam module. 

The LED's are on during imaging when the average light intensity of the picture is below a certain value. This was tweaked in our lab but may not be sufficient for your use case. In the log output you posted, the average light intensity of the picture was 17.7. The system considers anything above 10 (on a scale of 0–255) to be "daylight".

If there is need, I might add an option to tweak the day/night threshold in the web UI. Please open a separate issue if you need it! :)
