### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by abajrachgo** [jonasoh/spiro#36]
Hi guys

Kudos to you for making such a machine, and thanks for sharing the resources. 
I have assembled everything and have installed the Raspberry Pi (Legacy) as well as SPIRO according to the instructions. But after I access the SPIRO hotspot through WiFi and set the new password, I get an error:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Please let me know how to solve this issue. Keep up the good work!

Abhishesh

**Comment by jonasoh** [comment]
Hi Abhishesh,
congratulations on building your SPIRO, hope you will get good use out of it! :) 

This looks like a bug for sure. I will need a little more information to be able to narrow it down though. 

Could you log in via ssh and enter the following command: `journalctl --user-unit=spiro -n 200 --no-pager` and copy the results here?

**Comment by abajrachgo** [comment]
By ssh, do you mean that I should access spiro.local:22 via hotspot? If so, that gives me a 'This site cannot be reached' error.

I did try to enter the command into the raspberrypi command prompt and got these results (attached).

I hope the picture is clear enough. Thanks for the quick reply!

![IMG_20220211_091827551_HDR](https://user-images.githubusercontent.com/99422687/153619813-3a5aa30a-f117-4e15-ae29-8a96784bb7fe.jpg)

**Comment by jonasoh** [comment]
Ah, it was due to a mistake in one of the installation files. I will commit a fix. Please update your spiro installation by running the command `sudo pip3 install git+https://github.com/jonasoh/spiro#egg=spiro` and then restarting the service through `systemctl --user restart spiro`.

**Comment by jonasoh** [comment]
Sorry, that should be `sudo pip3 install -U git+https://github.com/jonasoh/spiro#egg=spiro`.

**Comment by abajrachgo** [comment]
Worked like a charm! Thanks @jonasoh! You guys are the best!

**Comment by jonasoh** [comment]
Happy to help, hope you get good use out of your SPIRO!
