### ISSUE TITLE
[bug] Flask upgrade

### ISSUE THREAD

**Issue by tsdobbs** [jonasoh/spiro#39]
On `spiro --install`, Python reports an import error `cannot import 'escape' from 'jinja2'`. This is a known issue for Flask projects, as [the latest version of jinja2 deprecated `escape`](https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2). Upgrading to the latest version of Flask fixes this, so I suggest bumping the Flask version number in the package.

**Comment by jonasoh** [comment]
Thanks for the heads up! Will have a look this week.
