### ISSUE TITLE
"dnsmasq.service not found" while enabling hotspot

### ISSUE THREAD

**Issue by AlyonaMinina** [jonasoh/spiro#48]
"sudo spiro --enable-hotspot" yields "Unit dnsmasq.service not found" and failed access point setting up.

The issue can be resolved by running "sudo apt install dnsmasq" prior to enabling the hotspot

**Comment by jonasoh** [comment]
This was fixed in 7a41234d428cbe3e22bd26748e955ef5e12f5d06 by amending the install instructions.
